### ISSUE TITLE
[mev-custom-flood] No new transactions created after 25 minutes of flooding

### ISSUE THREAD

**Issue by kamilchodola** [kurtosis-tech/ethereum-package#245]
Running mev_type:full with enabled custom flooder.

It is nicely filling up blocks with 4 transaction per slot but after some time (in my case 25 minutes) it just hanged on eth_chainId request and not moving forward (but container is still alive).

Logs from this case:
[custom-flood.log](https://github.com/kurtosis-tech/ethereum-package/files/12748638/custom-flood.log)

**Comment by piwonskp** [comment]
The script appears to be crashing (there is no process in the container) after sending ~474 transactions. I've tried to manually run the script in the container after crash.  Same situation - crashed after sending 481 transactions this time. Traceback:
```
Traceback (most recent call last):
  File "/tmp/sender.py", line 60, in <module>
    flood()
  File "/tmp/sender.py", line 47, in flood
    estimated_gas = w3.eth.estimate_gas(transaction)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/web3/eth/eth.py", line 293, in estimate_gas
    return self._estimate_gas(transaction, block_identifier)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/web3/module.py", line 75, in caller
    result = w3.manager.request_blocking(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/web3/manager.py", line 320, in request_blocking
    response = self._make_request(method, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/web3/manager.py", line 208, in _make_request
    return request_func(method, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/web3/middleware/signing.py", line 169, in middleware
    return make_request(method, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/web3/middleware/signing.py", line 169, in middleware
    return make_request(method, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/web3/middleware/signing.py", line 169, in middleware
    return make_request(method, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 474 more times]
  File "/usr/local/lib/python3.11/site-packages/web3/middleware/gas_price_strategy.py", line 101, in middleware
    return make_request(method, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/web3/middleware/formatting.py", line 106, in middleware
    response = make_request(method, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/web3/middleware/attrdict.py", line 43, in middleware
    response = make_request(method, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/web3/middleware/formatting.py", line 99, in middleware
    web3_formatters_builder(w3, method),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/web3/middleware/validation.py", line 142, in build_method_validators
    w3_chain_id = w3.eth.chain_id
                  ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/web3/eth/eth.py", line 145, in chain_id
    return self._chain_id()
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/web3/module.py", line 75, in caller
    result = w3.manager.request_blocking(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/web3/manager.py", line 320, in request_blocking
    response = self._make_request(method, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/web3/manager.py", line 208, in _make_request
    return request_func(method, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/web3/middleware/signing.py", line 169, in middleware
    return make_request(method, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/web3/middleware/signing.py", line 169, in middleware
    return make_request(method, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/web3/middleware/signing.py", line 169, in middleware
    return make_request(method, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 474 more times]
  File "/usr/local/lib/python3.11/site-packages/web3/middleware/gas_price_strategy.py", line 101, in middleware
    return make_request(method, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/web3/middleware/formatting.py", line 106, in middleware
    response = make_request(method, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/web3/middleware/attrdict.py", line 43, in middleware
    response = make_request(method, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/web3/middleware/formatting.py", line 106, in middleware
    response = make_request(method, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/web3/middleware/formatting.py", line 106, in middleware
    response = make_request(method, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/web3/middleware/buffered_gas_estimate.py", line 43, in middleware
    return make_request(method, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/web3/middleware/exception_retry_request.py", line 115, in middleware
    return make_request(method, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/web3/providers/rpc.py", line 90, in make_request
    raw_response = make_post_request(
                   ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/web3/_utils/request.py", line 114, in make_post_request
    response = get_response_from_post_request(endpoint_uri, data=data, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/web3/_utils/request.py", line 107, in get_response_from_post_request
    response = session.post(endpoint_uri, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/http/client.py", line 1378, in getresponse
    response.begin()
  File "/usr/local/lib/python3.11/http/client.py", line 337, in begin
    self.headers = self.msg = parse_headers(self.fp)
                              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/http/client.py", line 236, in parse_headers
    return email.parser.Parser(_class=_class).parsestr(hstring)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/email/parser.py", line 67, in parsestr
    return self.parse(StringIO(text), headersonly=headersonly)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/email/parser.py", line 56, in parse
    feedparser.feed(data)
  File "/usr/local/lib/python3.11/email/feedparser.py", line 174, in feed
    self._call_parse()
  File "/usr/local/lib/python3.11/email/feedparser.py", line 178, in _call_parse
    self._parse()
  File "/usr/local/lib/python3.11/email/feedparser.py", line 293, in _parsegen
    if self._cur.get_content_maintype() == 'message':
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/email/message.py", line 621, in get_content_maintype
    ctype = self.get_content_type()
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/email/message.py", line 605, in get_content_type
    value = self.get('content-type', missing)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/email/message.py", line 498, in get
    return self.policy.header_fetch_parse(k, v)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/email/_policybase.py", line 316, in header_fetch_parse
    return self._sanitize_header(name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/email/_policybase.py", line 287, in _sanitize_header
    if _has_surrogates(value):
       ^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded
```

**Comment by bharath-123** [comment]
+1 I face this issue too
