### ISSUE TITLE
Cannot set up a network with Besu

### ISSUE THREAD

**Issue by bsamuels453** [kurtosis-tech/ethereum-package#477]
error logs:
```
2024-01-30 19:04:28.597+00:00 | main | INFO  | Besu | Security Module: localfile
2024-01-30 19:04:28.768+00:00 | main | INFO  | Besu | Using the native implementation of alt bn128
2024-01-30 19:04:28.865+00:00 | main | INFO  | Besu | Using the native implementation of modexp
2024-01-30 19:04:28.865+00:00 | main | INFO  | Besu | Using the native implementation of the signature algorithm
2024-01-30 19:04:28.878+00:00 | main | INFO  | Besu | Using the native implementation of the blake2bf algorithm
2024-01-30 19:04:28.890+00:00 | main | INFO  | KZGPointEvalPrecompiledContract | Loading network trusted setup from classpath resource /kzg-trusted-setups/mainnet.txt
2024-01-30 19:04:29.697+00:00 | main | ERROR | Besu | Failed to start Besu
picocli.CommandLine$ExecutionException: Cannot store generated private key.
	at org.hyperledger.besu.cli.BesuCommand.buildController(BesuCommand.java:2158)
	at org.hyperledger.besu.cli.BesuCommand.initController(BesuCommand.java:2144)
	at org.hyperledger.besu.cli.BesuCommand.run(BesuCommand.java:1456)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at org.hyperledger.besu.cli.util.ConfigOptionSearchAndRunHandler.handle(ConfigOptionSearchAndRunHandler.java:61)
	at org.hyperledger.besu.cli.util.ConfigOptionSearchAndRunHandler.handle(ConfigOptionSearchAndRunHandler.java:33)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at org.hyperledger.besu.cli.BesuCommand.parse(BesuCommand.java:1621)
	at org.hyperledger.besu.cli.BesuCommand.parse(BesuCommand.java:1417)
	at org.hyperledger.besu.Besu.main(Besu.java:39)
Caused by: java.lang.IllegalArgumentException: Cannot store generated private key.
	at org.hyperledger.besu.crypto.KeyPairUtil.storeKeyFile(KeyPairUtil.java:125)
	at org.hyperledger.besu.crypto.KeyPairUtil.loadKeyPair(KeyPairUtil.java:94)
	at org.hyperledger.besu.cli.BesuCommand.loadKeyPair(BesuCommand.java:1601)
	at org.hyperledger.besu.cli.BesuCommand.defaultSecurityModule(BesuCommand.java:1589)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:181)
	at org.hyperledger.besu.cli.BesuCommand.securityModule(BesuCommand.java:3162)
	at org.hyperledger.besu.cli.BesuCommand.getControllerBuilder(BesuCommand.java:2180)
	at org.hyperledger.besu.cli.BesuCommand.buildController(BesuCommand.java:2156)
	... 18 more
Cannot store generated private key.
```

network config:
```
participants:
    - el_client_type: nethermind
      el_client_image: nethermind/nethermind:1.25.1
      cl_client_type: lighthouse
      cl_client_image: sigp/lighthouse:latest
      el_min_cpu: 1000
      el_max_cpu: 1000
      el_min_mem: 1024
      el_max_mem: 1024
      bn_min_cpu: 1000
      bn_max_cpu: 1000
      bn_min_mem: 2048
      bn_max_mem: 2048
      v_min_cpu: 1000
      v_max_cpu: 1000
      v_min_mem: 1024
      v_max_mem: 1024
      count: 1
    - el_client_type: besu
      el_client_image: hyperledger/besu:latest
      cl_client_type: lighthouse
      cl_client_image: sigp/lighthouse:latest
      el_min_cpu: 1000
      el_max_cpu: 1000
      el_min_mem: 1024
      el_max_mem: 1024
      bn_min_cpu: 1000
      bn_max_cpu: 1000
      bn_min_mem: 2048
      bn_max_mem: 2048
      v_min_cpu: 1000
      v_max_cpu: 1000
      v_min_mem: 1024
      v_max_mem: 1024
      count: 1
    - el_client_type: besu
      el_client_image: hyperledger/besu:latest
      cl_client_type: prysm
      cl_client_image: prysmaticlabs/prysm-beacon-chain:latest,prysmaticlabs/prysm-validator:latest
      el_min_cpu: 1000
      el_max_cpu: 1000
      el_min_mem: 1024
      el_max_mem: 1024
      bn_min_cpu: 1000
      bn_max_cpu: 1000
      bn_min_mem: 2048
      bn_max_mem: 2048
      v_min_cpu: 1000
      v_max_cpu: 1000
      v_min_mem: 1024
      v_max_mem: 1024
      count: 1
    - el_client_type: besu
      el_client_image: hyperledger/besu:latest
      cl_client_type: lodestar
      cl_client_image: chainsafe/lodestar:v1.12.1
      el_min_cpu: 1000
      el_max_cpu: 1000
      el_min_mem: 1024
      el_max_mem: 1024
      bn_min_cpu: 1000
      bn_max_cpu: 1000
      bn_min_mem: 2048
      bn_max_mem: 2048
      v_min_cpu: 1000
      v_max_cpu: 1000
      v_min_mem: 1024
      v_max_mem: 1024
      count: 1
network_params:
    num_validator_keys_per_node: 32
additional_services:
    - prometheus_grafana
    - dora
parallel_keystore_generation: false
persistent: true

```

besu images tested:
- latest
- 24.1.1
- 23.10.3

kurtosis version (cli and engine): 0.86.12

**Comment by bsamuels453** [comment]
false positive
