### ISSUE TITLE
Can't start teku on persistent networks

### ISSUE THREAD

**Issue by bsamuels453** [kurtosis-tech/ethereum-package#478]
error only happens when persistent: true
no error when persistence is disabled

err logs:
```
➜  ~ k logs cl-1-teku-nethermind -f
Defaulted container "user-service-container" out of: user-service-container, files-artifact-expander (init)
INFO StatusConsoleListener Setting logging level to INFO
INFO StatusConsoleListener Configuring logging for destination: console
INFO StatusConsoleListener Logging includes events: true
INFO StatusConsoleListener Logging includes validator duties: true
INFO StatusConsoleListener Logging includes color: true
INFO StatusConsoleListener Include P2P warnings set to: false
2024-01-30 19:41:44.785 INFO  - Teku version: teku/v23.12.0/linux-x86_64/-eclipseadoptium-openjdk64bitservervm-java-17
2024-01-30 19:41:44.791 INFO  - This software is licensed under the Apache License, Version 2.0 (the "License"); you may not use this software except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
2024-01-30 19:41:45.204 INFO  - Configuration | Network: empty, Storage Mode: ARCHIVE
2024-01-30 19:41:45.204 INFO  - Host Configuration | Maximum Heap Size: 0.46 GB, Total Memory: 15.62 GB, CPU Cores: 8
2024-01-30 19:41:45.204 INFO  - Rest Api Configuration | Enabled: true, Listen Address: 0.0.0.0, Port: 4000, Allow: [*]
2024-01-30 19:41:45.204 INFO  - Validator Api Configuration | Listen Address: 0.0.0.0, Port 5052, Allow: [127.0.0.1, localhost]
2024-01-30 19:41:46.103 INFO  - JWT secret loaded from /jwt/jwtsecret
2024-01-30 19:41:46.118 INFO  - Using execution engine at http://10.245.154.51:8551
2024-01-30 19:41:46.118 INFO  - Enabling Builder Circuit Breaker
2024-01-30 19:41:46.320 INFO  - Eth1 endpoint not provided, using execution engine endpoint for eth1 data
2024-01-30 19:41:46.490 FATAL - Teku failed to start
java.lang.IllegalStateException: Could not create slashing protection path: Unable to create directory /opt/teku/teku-beacon-data/validator/slashprotection
at tech.pegasys.teku.infrastructure.io.SyncDataAccessor.create(SyncDataAccessor.java:58) ~[teku-infrastructure-io-23.12.0.jar:23.12.0]
at tech.pegasys.teku.validator.client.ValidatorClientService.createValidatorLoader(ValidatorClientService.java:375) ~[teku-validator-client-23.12.0.jar:23.12.0]
at tech.pegasys.teku.validator.client.ValidatorClientService.create(ValidatorClientService.java:147) ~[teku-validator-client-23.12.0.jar:23.12.0]
at tech.pegasys.teku.services.BeaconNodeServiceController.<init>(BeaconNodeServiceController.java:56) ~[teku-23.12.0.jar:23.12.0]
at tech.pegasys.teku.BeaconNode.<init>(BeaconNode.java:27) ~[teku-23.12.0.jar:23.12.0]
at tech.pegasys.teku.Teku.start(Teku.java:71) ~[teku-23.12.0.jar:23.12.0]
at tech.pegasys.teku.Teku.lambda$startFromCLIArgs$2(Teku.java:86) ~[teku-23.12.0.jar:23.12.0]
at tech.pegasys.teku.cli.BeaconNodeCommand.call(BeaconNodeCommand.java:340) [teku-23.12.0.jar:23.12.0]
at tech.pegasys.teku.cli.BeaconNodeCommand.call(BeaconNodeCommand.java:78) [teku-23.12.0.jar:23.12.0]
at picocli.CommandLine.executeUserObject(CommandLine.java:2041) [picocli-4.7.5.jar:4.7.5]
Teku failed to start: Could not create slashing protection path: Unable to create directory /opt/teku/teku-beacon-data/validator/slashprotection

To display full help:
teku [COMMAND] --help
at picocli.CommandLine.access$1500(CommandLine.java:148) [picocli-4.7.5.jar:4.7.5]
at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461) [picocli-4.7.5.jar:4.7.5]
at picocli.CommandLine$RunLast.handle(CommandLine.java:2453) [picocli-4.7.5.jar:4.7.5]
at picocli.CommandLine$RunLast.handle(CommandLine.java:2415) [picocli-4.7.5.jar:4.7.5]
at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273) [picocli-4.7.5.jar:4.7.5]
at picocli.CommandLine$RunLast.execute(CommandLine.java:2417) [picocli-4.7.5.jar:4.7.5]
at picocli.CommandLine.execute(CommandLine.java:2170) [picocli-4.7.5.jar:4.7.5]
at tech.pegasys.teku.cli.BeaconNodeCommand.parse(BeaconNodeCommand.java:272) [teku-23.12.0.jar:23.12.0]
at tech.pegasys.teku.Teku.start(Teku.java:63) [teku-23.12.0.jar:23.12.0]
at tech.pegasys.teku.Teku.startFromCLIArgs(Teku.java:86) [teku-23.12.0.jar:23.12.0]
at tech.pegasys.teku.Teku.main(Teku.java:40) [teku-23.12.0.jar:23.12.0]
```

Kurtosis 0.86.12

network config:
```
participants:
    - el_client_type: nethermind
      el_client_image: nethermind/nethermind:1.25.1
      cl_client_type: teku
      cl_client_image: consensys/teku:23.12.0
      el_min_cpu: 1000
      el_max_cpu: 1000
      el_min_mem: 1024
      el_max_mem: 1024
      bn_min_cpu: 1000
      bn_max_cpu: 1000
      bn_min_mem: 2048
      bn_max_mem: 2048
      count: 1
    - el_client_type: nethermind
      el_client_image: nethermind/nethermind:1.25.1
      cl_client_type: lighthouse
      cl_client_image: sigp/lighthouse:latest
      el_min_cpu: 1000
      el_max_cpu: 1000
      el_min_mem: 1024
      el_max_mem: 1024
      bn_min_cpu: 1000
      bn_max_cpu: 1000
      bn_min_mem: 2048
      bn_max_mem: 2048
      v_min_cpu: 1000
      v_max_cpu: 1000
      v_min_mem: 1024
      v_max_mem: 1024
      count: 1
    - el_client_type: nethermind
      el_client_image: nethermind/nethermind:1.25.1
      cl_client_type: lighthouse
      cl_client_image: sigp/lighthouse:latest
      el_min_cpu: 1000
      el_max_cpu: 1000
      el_min_mem: 1024
      el_max_mem: 1024
      bn_min_cpu: 1000
      bn_max_cpu: 1000
      bn_min_mem: 2048
      bn_max_mem: 2048
      v_min_cpu: 1000
      v_max_cpu: 1000
      v_min_mem: 1024
      v_max_mem: 1024
      count: 1
    - el_client_type: nethermind
      el_client_image: nethermind/nethermind:1.25.1
      cl_client_type: prysm
      cl_client_image: prysmaticlabs/prysm-beacon-chain:latest,prysmaticlabs/prysm-validator:latest
      el_min_cpu: 1000
      el_max_cpu: 1000
      el_min_mem: 1024
      el_max_mem: 1024
      bn_min_cpu: 1000
      bn_max_cpu: 1000
      bn_min_mem: 2048
      bn_max_mem: 2048
      v_min_cpu: 1000
      v_max_cpu: 1000
      v_min_mem: 1024
      v_max_mem: 1024
      count: 1
    - el_client_type: nethermind
      el_client_image: nethermind/nethermind:1.25.1
      cl_client_type: lodestar
      cl_client_image: chainsafe/lodestar:v1.12.1
      el_min_cpu: 1000
      el_max_cpu: 1000
      el_min_mem: 1024
      el_max_mem: 1024
      bn_min_cpu: 1000
      bn_max_cpu: 1000
      bn_min_mem: 2048
      bn_max_mem: 2048
      v_min_cpu: 1000
      v_max_cpu: 1000
      v_min_mem: 1024
      v_max_mem: 1024
      count: 1
network_params:
    num_validator_keys_per_node: 32
additional_services:
    - prometheus_grafana
    - dora
parallel_keystore_generation: false
persistent: true

```

**Comment by bsamuels453** [comment]
ignore, misconfigured something
